import io
import re
from datetime import datetime
from xml.sax.saxutils import escape

import bleach
import markdown as md
from bs4 import BeautifulSoup
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import HRFlowable, PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

MARKDOWN_EXTENSIONS = ["tables", "fenced_code"]

ALLOWED_TAGS = [
    "p", "br", "hr", "h1", "h2", "h3", "h4", "h5", "h6",
    "strong", "em", "u", "code", "pre", "blockquote",
    "ul", "ol", "li",
    "table", "thead", "tbody", "tr", "th", "td",
]
ALLOWED_ATTRIBUTES = {
    "th": ["colspan", "rowspan"],
    "td": ["colspan", "rowspan"],
    "code": ["class"],
}


def markdown_to_html(markdown_text):
    raw_html = md.markdown(markdown_text or "", extensions=MARKDOWN_EXTENSIONS)
    clean_html = bleach.clean(
        raw_html,
        tags=ALLOWED_TAGS,
        attributes=ALLOWED_ATTRIBUTES,
        strip=True,
    )
    return clean_html


def _extract_title(markdown_text):
    for line in (markdown_text or "").splitlines():
        stripped = line.strip()
        if stripped.startswith("# "):
            return stripped[2:].strip()
        if stripped.startswith("## "):
            return stripped[3:].strip()
    return "Exam Revision Notes"


def _extract_subject(markdown_text):
    match = re.search(r"(?im)^subject\s*:\s*(.+)$", markdown_text or "")
    if match:
        return match.group(1).strip()
    return "General Study"


def _inline_markdown_to_reportlab(text):
    safe = escape(text or "")
    # Allow explicit underline tags from model output.
    safe = safe.replace("&lt;u&gt;", "<u>").replace("&lt;/u&gt;", "</u>")
    safe = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", safe)
    safe = re.sub(r"__(.+?)__", r"<b>\1</b>", safe)
    safe = re.sub(r"\*(.+?)\*", r"<i>\1</i>", safe)
    safe = re.sub(r"_(.+?)_", r"<i>\1</i>", safe)
    safe = re.sub(r"`(.+?)`", r"<font name='Courier'>\1</font>", safe)
    return safe


def _add_footer(canvas, _doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 8.5)
    canvas.setFillColor(colors.HexColor("#475569"))
    canvas.drawString(0.72 * inch, 0.45 * inch, "Generated by Corneal AI - AI Exam Assistant")
    canvas.drawRightString(7.78 * inch, 0.45 * inch, f"Page {canvas.getPageNumber()}")
    canvas.restoreState()


def generate_pdf(markdown_text):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=52,
        rightMargin=52,
        topMargin=56,
        bottomMargin=54,
        title="Study Notes"
    )
    styles = getSampleStyleSheet()
    cover_title = ParagraphStyle(
        "CoverTitle", parent=styles["Title"], fontName="Helvetica-Bold", fontSize=26, leading=32, textColor=colors.HexColor("#0f172a")
    )
    cover_meta = ParagraphStyle(
        "CoverMeta", parent=styles["BodyText"], fontName="Helvetica", fontSize=12, leading=18, textColor=colors.HexColor("#334155")
    )
    body = ParagraphStyle("Body", parent=styles["BodyText"], fontName="Helvetica", fontSize=10.5, leading=16, spaceAfter=5)
    h1 = ParagraphStyle("H1", parent=styles["Heading1"], fontName="Helvetica-Bold", fontSize=18, leading=24, spaceBefore=8, spaceAfter=8, textColor=colors.HexColor("#0f172a"))
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], fontName="Helvetica-Bold", fontSize=14.5, leading=20, spaceBefore=8, spaceAfter=6, textColor=colors.HexColor("#1e293b"))
    h3 = ParagraphStyle("H3", parent=styles["Heading3"], fontName="Helvetica-Bold", fontSize=12, leading=16, spaceBefore=6, spaceAfter=4, textColor=colors.HexColor("#334155"))
    bullet = ParagraphStyle("Bullet", parent=body, leftIndent=14, firstLineIndent=-8, spaceAfter=4)

    elements = []
    topic = _extract_title(markdown_text)
    subject = _extract_subject(markdown_text)
    generated_on = datetime.utcnow().strftime("%B %d, %Y")

    # Cover page
    elements.append(Spacer(1, 1.25 * inch))
    elements.append(Paragraph(escape(topic), cover_title))
    elements.append(Spacer(1, 0.2 * inch))
    elements.append(Paragraph(f"<b>Subject:</b> {escape(subject)}", cover_meta))
    elements.append(Paragraph("<b>Generated by:</b> Corneal AI", cover_meta))
    elements.append(Paragraph(f"<b>Date:</b> {generated_on}", cover_meta))
    elements.append(Spacer(1, 0.35 * inch))
    elements.append(HRFlowable(width="100%", thickness=1.0, color=colors.HexColor("#cbd5e1"), spaceBefore=4, spaceAfter=8))
    elements.append(Paragraph("Printable Exam Revision Booklet", cover_meta))
    elements.append(PageBreak())

    html = markdown_to_html(markdown_text)
    soup = BeautifulSoup(html, "html.parser")

    for node in soup.children:
        name = getattr(node, "name", None)
        if name is None:
            continue

        if name == "h1":
            elements.append(Paragraph(_inline_markdown_to_reportlab(node.get_text(" ", strip=True)), h1))
            elements.append(HRFlowable(width="100%", thickness=0.8, color=colors.HexColor("#cbd5e1"), spaceBefore=2, spaceAfter=6))
            continue
        if name == "h2":
            elements.append(Paragraph(_inline_markdown_to_reportlab(node.get_text(" ", strip=True)), h2))
            continue
        if name == "h3":
            elements.append(Paragraph(_inline_markdown_to_reportlab(node.get_text(" ", strip=True)), h3))
            continue
        if name in {"p", "blockquote"}:
            text = node.get_text(" ", strip=True)
            if text:
                elements.append(Paragraph(_inline_markdown_to_reportlab(text), body))
            continue
        if name in {"ul", "ol"}:
            for idx, li in enumerate(node.find_all("li", recursive=False), start=1):
                content = _inline_markdown_to_reportlab(li.get_text(" ", strip=True))
                if name == "ol":
                    elements.append(Paragraph(f"{idx}. {content}", bullet))
                else:
                    elements.append(Paragraph(f"&bull; {content}", bullet))
            continue
        if name == "table":
            rows = []
            for row in node.find_all("tr"):
                cells = row.find_all(["th", "td"])
                rows.append([Paragraph(_inline_markdown_to_reportlab(cell.get_text(" ", strip=True)), body) for cell in cells])

            if rows:
                col_width = (doc.width / max(len(rows[0]), 1))
                table = Table(rows, colWidths=[col_width] * len(rows[0]), hAlign="LEFT")
                table.setStyle(
                    TableStyle(
                        [
                            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e2e8f0")),
                            ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
                            ("GRID", (0, 0), (-1, -1), 0.6, colors.HexColor("#94a3b8")),
                            ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                            ("VALIGN", (0, 0), (-1, -1), "TOP"),
                            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                            ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
                            ("LEFTPADDING", (0, 0), (-1, -1), 6),
                            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                            ("TOPPADDING", (0, 0), (-1, -1), 5),
                            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                        ]
                    )
                )
                elements.append(table)
                elements.append(Spacer(1, 8))
            continue
        if name == "hr":
            elements.append(HRFlowable(width="100%", thickness=0.8, color=colors.HexColor("#cbd5e1"), spaceBefore=4, spaceAfter=6))
            continue

    if len(elements) <= 2:
        elements.append(Paragraph(_inline_markdown_to_reportlab(markdown_text or ""), body))

    doc.build(elements, onFirstPage=_add_footer, onLaterPages=_add_footer)
    buffer.seek(0)
    return buffer
